FROM rust:1.56.0@sha256:927125be1befca4e0f91a81a73cf1108f7552297ab8311d9fbf55b03f1c9246f
RUN curl -sL https://github.com/rust-analyzer/rust-analyzer/releases/download/2021-11-01/rust-analyzer-x86_64-unknown-linux-gnu.gz --output rust-analyzer.gz
RUN gunzip rust-analyzer.gz
